FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris
ENV PREFIX='/usr/local/etc/oai'
ENV Cassandra_Server_IP='192.168.0.3'
ENV MY_REALM='home.lab'

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git sudo gnupg2 && \
    apt-get clean && \
    git clone https://github.com/tramed/openair-cn.git

WORKDIR /openair-cn/scripts/

RUN git checkout review-master-dev && \
    ./build_hss_rel14 --check-installed-software --force && \
    ./build_hss_rel14 --clean && \
    apt-get clean

RUN apt-get install -y net-tools && \
    apt-get clean

WORKDIR /
COPY ./docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT [ "/docker-entrypoint.sh" ]

EXPOSE 9080 9081